language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

compiler:
  - gcc
  
install:
- sudo ./singularity_build.sh setup build

script:
- sudo ./singularity_build.sh install
