language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

compiler:
- gcc
  
before_install:
- chmod +x singularity_build.sh

install:
- sudo ./singularity_build.sh setup build

script:
- sudo ./singularity_build.sh install
